project:
  type: website
  output-dir: docs

website:
  title: "Ian Hulskamp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - interests.qmd
      - skills.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual


