---
title: "About"
---

¡Saludos! Mi nombre es Ian. Me encantaría decirte que tengo un apodo pero no, desafortunadamente aún no me han asignado ninguno del que me haya apropiado o se haya adoptado de forma extendida.

Crecí en el noroeste de la Patagonia Argentina hasta que emigré a estudiar economía en la Universidad de Buenos Aires. Si bien inicié la carrera con inocentes pretensiones de hacer política económica, una serie de eventos me acercaron a la filosofía de la ciencia y terminé siendo dos años becario de investigación en el Centro de Investigación en Epistemología de las Ciencias Económicas (CIECE). Desde entonces no he parado de estudiar, ni pienso hacerlo en el corto plazo. Considero "aprender", lo que sea, una de las pocas pasiones que tengo.

Mientras terminaba la carrera de licenciatura fui pasante y consultor en la Oficina de CEPAL en Buenos Aires. Aprendí muchísimo. Después hice una maestría doble en economía de la innovación y el conocimiento. Para no perder la costumbre, después empecé mi doctorado en la Sociedad de la Información y el Conocimiento. Actualmente, después de 3 años y medio y con un pandemia de por medio, me encuentro en la recta final de escribir mi tesis doctoral.

Juntando todas las etapas de este proceso, lo que mejor aprendí es a investigar. Justamente, en este espacio virtual la idea es compartir reflexiones con respecto al proceso de investigación la relación entre las teorías científicas y las observaciones empíricas. La idea sería algo así como explorar las complejidades de cómo adquirimos y entendemos el conocimiento y la realidad.

Además de mi trabajo académico, también disfruto de la práctica de deportes y la actividad física en general. Considero que el deporte es una forma de experimentar y explorar las capacidades de nuestro cuerpo, al igual que la ciencia es una forma de experimentar y explorar las capacidades de nuestra mente. La combinación de ambos aspectos me parece fascinante y enriquecedora.

Si deseas obtener más información sobre mi experiencia académica y profesional, puedes encontrar mi CV en [incluir un enlace a un CV en línea o en un sitio web]. Espero que este blog sea un espacio para reflexionar y discutir sobre temas filosóficos y científicos, así como para compartir ideas y aprendizajes. ¡Gracias por visitar!

email / resume / Twitter

---
## Especulación Científica

> "Examinar los asuntos de brujería es como tratar de entrar en la metafísica por la puerta de atrás. A mi juicio esta actitud es preferible a pasar de largo."

Este blog es mi compañero en el desgastante viaje en el que se ha convertido la finalización de mi tesis doctoral. Por lo tanto, este también es un espacio de catarsis, liberación creativa y auto-reflexión. Aquí, puedo explorar temas y pensamientos que quizás no caben en la escritura académica, permitiéndome jugar con ideas y perspectivas de manera más lúdica.

En este blog espero ofrecer un espacio compartido para quienes buscan explorar y contraponer ideas con respecto a temas que me apasionan. Si bien espero que este sea un espacio de intercambio, reflexión y aprendizaje con otros, lo hago, en última instancia, para mi.

Muchas entradas estarán marcadas por la frustración que surge al escribir una tesis (perdón por eso). Igualmente intentaré también reflejar mi entusiasmo por la investigación en cada post.

El hilo conductor de mis posteos será, justamente, la investigación. Al menos en un principio. Y estáran centrados en todos los procesos humanos, más de carácter especulativos, que rodean a la investigación científica.