---
title: "Especulación Científica"
listing:
  contents: posts # all QUarto docs in the 'posts' directory will be included on your listing page
  type: grid # either 'default', 'table', or 'custom'; each type has its own set of yaml options to include
  sort: "date desc" # sort can be done on more than one field
  categories: true # allows you to sort posts by assigned categories
bibliography: references.bib
---

> "Examinar los asuntos de brujería es como tratar de entrar en la metafísica por la puerta de atrás. A mi juicio esta actitud es preferible a pasar de largo."
>
> | *Alejandro Dolina [-@dolina1996, p. 146]*

::: justified
Todos buscamos respuestas, algunos en las expresión artística, otros en la experimentación científica. Este blog o wiki es un espacio donde yo expreso y explicito mi perspectiva, mi marco teórico, mi cosmología, o como uno quiera llamar aquello que nos inventamos para dar respuestas. A través de breves entradas, comparto reflexiones sobre cómo yo percibo aquello que me acontece.  

Más allá de ser un espacio para reflexionar y articular mis propios pensamientos, estás pensado también para intercambiar con otros. Así que si te despierta algún interés, idea, o sugerencia, compartímela. 

La idea es explorar temas de manera lúdica y progresiva, sin prisas. Las entradas están ordenadas por fecha más reciente pero aquí te dejo algunas bases: [el I-Space](posts/20231027-ispaceBasics/index.qmd); [Datos, información y conocimiento](/posts/20231111-dataInformationKnowledge/index.qmd); y [mis principios cosmológicos](/posts/20231028-cosmologicalPrinciples/index.qmd).
:::

------------------------------------------------------------------------
