---
toc: true
toc-title: "Interests/intereses"
toc-depth: 4
bibliography: references.bib
link-citations: false
# title-block-banner: true 
# title: "Professional and Academic Focus"
# subtitle: "In addition to my professional skills, my career has led me to explore various areas of knowledge that have left a mark on my worldview. Here, I describe some areas that have particularly captured my attention, including some references to my own work"
---

::: {.content-visible when-profile="es"}
# Enfoque Profesional y Acad茅mico

::: justified

He explorado diversas 谩reas de conocimiento a lo largo de mi carrera profesional, dando forma a mi perspectiva. A continuaci贸n, describo 谩reas clave que han capturado mi atenci贸n, con referencias a mis contribuciones cuando corresponda.

:::

------------------------------------------------------------------------

### Colaboraci贸n Academia-Industria (AIC)
<details>
<summary> ★ **Construyendo puentes para aumentar el impacto de las ideas**   </summary>

::: justified
<br>
La transferencia de conocimientos entre organizaciones acad茅micas y empresariales para promover la innovaci贸n es el tema principal en el que he estado trabajando durante los 煤ltimos 5 o 6 a帽os. Hasta ahora ha sido un proceso que involucr贸 la navegaci贸n entre m煤ltiples perspectivas, aumentando continuamente su complejidad:

* Mi inter茅s en el tema surgi贸 gracias al curso de Econom铆a del Conocimiento de mi Maestr铆a, donde un colega y yo exploramos el papel de las instituciones de investigaci贸n p煤blica en los procesos de recuperaci贸n mediante el an谩lisis del caso de India.

* La exploraci贸n del tema continu贸 con mi tesis de maestr铆a, titulada "University-Industry Relationship through Knowledge Transfer Organizations in Developing Countries: Evidence from an Argentinian Local Innovation Ecosystem".

* El reciente solicitud de dep贸sito de mi Tesis Doctoral, titulada "Understanding Knowledge Dynamics Across Modes of Academia-Industry Collaboration:
A Comprehensive Mixed-Method Analysis within the I-Space Framework: Lessons from San Carlos de Bariloche, Argentina", representa la 煤ltima y m谩s profunda etapa de este proceso.

:::

</details>

### Gesti贸n del Conocimiento y Aprendizaje Organizacional
<details>
<summary> **Dise帽ando estrategias para la producci贸n colectiva de conocimiento**  </summary>

::: justified
<br>
Un tema cr铆tico que estudi茅 para mi doctorado y que me motiva a abordar la implementaci贸n del conocimiento.

* Dado que no he contribuido mucho al campo hasta ahora, deber铆a destacar el marco te贸rico desarrollado por Boisot [-@boisot1995] para comprender los flujos de informaci贸n y conocimiento en entornos sociales: el *Information Space* o *I-Space*. En mi [**blog**](blog.qmd), estoy intentando sintetizar y usar este marco para analizar la coyuntura.

* Codificaci贸n, abstracci贸n y difusi贸n son tres dimensiones clave utilizadas para analizar la producci贸n continua de conocimiento [@boisot2011].

* Adem谩s del Espacio I, otras perspectivas tambi茅n han dado forma a mi comprensi贸n del campo [e.g., @alavi2001; @cetina1999; @march1991; @nonaka1995; @polanyi1958; @teece1997].

:::
</details>

### Econom铆a, Instituciones y Cultura
<details>

<summary> **Explorando los fundamentos socioculturales del comportamiento econ贸mico y humano**  </summary>

::: justified
<br>
驴C贸mo definen la gesti贸n de recursos, informaci贸n y conocimiento la cultura y los arreglos institucionales?


* Adem谩s de explorar las Colaboraciones Academia-Industria, con otra compa帽era de clase de la maestr铆a realizamos un an谩lisis de hackerspaces y makerspaces basado en la idea de bienes comunes de Ostrom [-@ostrom1990].

* M谩s all谩 de mi contribuci贸n limitada al tema, vale la pena mencionar algunos enfoques como sistemas de innovaci贸n [@cooke2001; @etzkowitz2000; @lundvall1988; @nelson1993], innovaci贸n abierta [@chesbrough2003; @vonhippel2005], bienes comunes [@allen2016; @hess2007; @kostakis2015; @ostrom1990] y econom铆a de la informaci贸n [@boisot1998].

:::

</details>

### Plataformas y Digitalizaci贸n

<details>
<summary> **Transitando la Era Digital**  </summary>

::: justified
<br>
La continua proliferaci贸n de tecnolog铆as de la informaci贸n y la comunicaci贸n (TIC) tiene un fuerte impacto en la producci贸n de conocimiento e informaci贸n.

* Con mi supervisor de doctorado hemos explorado ampliamente los [fundamentos de las plataformas digitales y su clasificaci贸n](https://comein.uoc.edu/divulgacio/oikonomics/_recursos/documents/14/canals-hulskamp_Oikonomics14_esp.pdf).

* Me siento particularmente atra铆do por perspectivas te贸ricas como la de Gawer [-@gawer2020]. Creo que entender c贸mo estas plataformas est谩n remodelando las interacciones econ贸micas y sociales es fundamental. 

:::

</details>

### Teor铆a de Grafos y An谩lisis de Redes
<details>
<summary> **Descubriendo relaciones m谩s all谩 de los actores** </summary>
::: justified
<br>
Representando la complejidad como sistemas interconectados e interdependientes, considerando tanto los nodos como los v铆nculos que los conectan [@b枚rner2007; @granovetter1973; @granovetter1983; @newman2018]. 

* He trabajado con bases de datos bibliom茅tricas y datos de encuestas para analizar procesos de colaboraci贸n entre investigadores y entre partes interesadas acad茅micas y empresariales. [**Aqu铆**](visualMedia/hulskampPresentation.mp4) puedes ver mi presentaci贸n "Scientific Collaboration through Institutional Networks: The Value of National Partners" en la conferencia [NetSci 2021](https://networks2021.net/).

:::
</details>

### Filosof铆a, Educaci贸n, Psicolog铆a: Pragmatismo y Enactivismo.
<details>
<summary> **Filosof铆a en acci贸n**  </summary>
::: justified
<br>
He explorado enfoques pragmatistas y enactivistas [e.g., @dewey1923; @varela2017], as铆 como su aplicaci贸n en campos como la educaci贸n y la psicolog铆a [e.g., @bereiter2014; @kress2009; @scardamalia2010].

* Como parte de mi tesis de grado y como becario de investigaci贸n en CIECE, investigu茅 c贸mo los modelos econ贸micos suelen fallar al intentar representar la complejidad.  
:::

</details>

### Teor铆a de la Complejidad y Teor铆a de la Informaci贸n
<details>
<summary>З **Explorando la complejidad de los fen贸menos** </summary>

::: justified
<br>
Entusiasmo por las propiedades emergentes, la entrop铆a [@ben-naim2008], el trabajo revolucionario de Claude Shannon [-@shannon1949], y estudios posteriores en diversas 谩reas de conocimiento [e.g., @boisot2004; @gleick2011; @snowden2002; @polyanskiy2022]. Recientemente particip茅 en un interesante [curso](https://www.youtube.com/@redcompleja4990) sobre redes complejas.  

:::

</details>

### Zettelkasten
<details>
<summary> **Organizaci贸n creativa** く</summary>
::: justified
<br>
La t茅cnica [**Zettelkasten**](https://docs.zettlr.com/en/advanced/zkn-method/) como fuente de generaci贸n de ideas y organizaci贸n del pensamiento [@ahrens2022].
:::
</details>

### Idiomas
<details>
<summary> **Conectando a trav茅s del lenguaje** </summary>
::: justified
<br>
Mi pasi贸n por comprender las diferencias culturales y los patrones de comunicaci贸n inevitablemente me ha llevado a aprender varios idiomas. Adem谩s de mi fluidez en espa帽ol, ingl茅s, italiano, sigo estudiando activamente el catal谩n y puedo comunicarme en franc茅s. Me encantar铆a seguir aprendiendo otros idiomas.
:::

</details>

:::

<!-- English -->

::: {.content-visible when-profile="en"}
# Professional and Academic Focus 


::: justified
I've delved into diverse knowledge areas throughout my professional career, shaping my perspective. Below, I outline key areas that have captured my attention, with references to my contributions where relevant.
:::

------------------------------------------------------------------------

### Academia-Industry Collaboration (AIC)
<details>
<summary> ★ **Building bridges to increase the impact of ideas**   </summary>

::: justified
<br>
The transfer of knowledge between academic and business organizations to promote innovation is the main subject I have been working on for the last 5 or 6 years. So far it has been a process which involved navigating multiple perspectives, continuously increasing in its complexity:

* My interest in the subject appeared thanks to the Economics of Knowledge course of my Master's, where a collegue and I explored the role of public research institutions in catching-up processes by analyzing the the case of India.

* The exploration of the subject continued with my Master's thesis, titled "University-Industry Relationship through Knowledge Transfer Organizations in Developing Countries: Evidence from an Argentinian Local Innovation Ecosystem"

* The recent submission of PhD Thesis, titled "Understanding Knowledge Dynamics Across Modes of Academia-Industry Collaboration:
A Comprehensive Mixed-Method Analysis within the I-Space Framework: Lessons from San Carlos de Bariloche, Argentina", represent the last and most profound stage of this process.

:::

</details>

### Knowledge Management and Organizational Learning
<details>
<summary> **Designing strategies for the collective production of knowledge**  </summary>

::: justified
<br>
A critical topic I studied for my doctorate and which motivates me to approach the implementation of knowledge. 

* Since I have not contributed much to the field so far, I should highlight the theoretical framework developed by Boisot [-@boisot1995] for understanding information and knowledge flows in social settings: the *Information Space* or *I-Space*. In my [**blog**](blog.qmd), I am now trying to synthesize and use this framework to analyze the conjuncture.

* Coding, abstraction, and diffusion are three key dimensions used to analyze the ongoing production of knowledge [@boisot2011].

* Besides the I-Space, other perspectives have also shaped my understanding of the field [e.g., @alavi2001; @cetina1999; @march1991; @nonaka1995; @polanyi1958; @teece1997].

:::
</details>

### Economics, Institutions, and Culture
<details>

<summary> **Exploring the socio-cultural foundations of economic and human behavior**  </summary>

::: justified
<br>
How culture and institutional arrangements define the management of resources, information, and knowledge? 

* Besides exploring Academia-Industry Collaborations, with another classmate of the master we made an analysis of hackerspace and makerspaces based on Ostrom's [-@ostrom1990] idea of commons.

* Beyond my limited contribution to the subject, a few approaches worth mentioning are innovation systems [@cooke2001; @etzkowitz2000; @lundvall1988; @nelson1993], open innovation [@chesbrough2003; @vonhippel2005], commons [@allen2016; @hess2007; @kostakis2015; @ostrom1990], and information economics [@boisot1998].

:::

</details>

### Platforms and Digitalization
<details>
<summary> **Navigating the Digital Age**  </summary>

::: justified
<br>
The continuous proliferation of information and communication technologies (ICTs) has a strong impact on the production of knowledge and information.

* With my PhD supervisor we've broadly explored the [foundations of digital platforms and their classification](https://comein.uoc.edu/divulgacio/oikonomics/_recursos/documents/14/canals-hulskamp_Oikonomics14_esp.pdf).

* I'm particularly drawn to theoretical perspectives like Gawer [-@gawer2020]. I believe understanding how these platforms are reshaping economic and social interactions is fundamental. 

:::

</details>

### Graph Theory and Network Analysis
<details>
<summary> **Unraveling relationships beyond the actors** </summary>
::: justified
<br>
Representing complexity as interconnected and interdependent systems, considering both nodes and the links that connect them [@b枚rner2007; @granovetter1973; @granovetter1983; @newman2018]. 

* I have worked with bibliometric databases and survey data to analyze collaboration processes among researchers and between academic and business stakeholders. [**Here**](visualMedia/hulskampPresentation.mp4) you can see my presentation "Scientific Collaboration through Institutional Networks: The Value of National Partners" at the [NetSci 2021](https://networks2021.net/) conference.

:::
</details>

### Philosophy: Pragmatism, Enactivism, Education, Psychology
<details>
<summary> **Philosophy in action**  </summary>
::: justified
<br>
I have explored pragmatism and enactivists approaches [e.g., @dewey1923; @varela2017], as well as their application in fields like education and psychology [e.g., @bereiter2014; @kress2009; @scardamalia2010].

* As part of my undergraduate thesis and as a research fellow at CIECE, I researched how economic models typically fail to successfully represent complexity.  
:::

</details>

### Complexity Theory and Information Theory
<details>
<summary>З **Exploring the complexity of phenomena** </summary>

::: justified
<br>
Enthusiasm for emergent properties, entropy [@ben-naim2008], the groundbreaking work of Claude Shannon [-@shannon1949], and subsequent studies in various knowledge areas [e.g., @boisot2004; @gleick2011; @snowden2002; @polyanskiy2022]. I recently participated in an interesting [course](https://www.youtube.com/@redcompleja4990) on complex networks.  

:::

</details>

### Zettelkasten
<details>
<summary> **Creative organization** く</summary>
::: justified
<br>
The [Zettelkasten technique](https://docs.zettlr.com/en/advanced/zkn-method/) as a source of idea generation and thought organization [@ahrens2022].
:::
</details>

### Languages
<details>
<summary> **Connecting through language** </summary>
::: justified
<br>
My passion for understanding cultural differences and communication patterns has inevitably led me to learn languages. In addition to my fluency in Spanish, English, Italian, and active study of Catalan, I can communicate in French. I would love to continue learning other languages.
:::

</details>

:::

